---
title: "Final Truck Model"
format: html
editor: visual
---

## 

```{r}
library(deSolve)
library(tidyverse)
```

Change the number of regions by changing N and then changing the number of variables to account for those regions. C should always be NxN, and all of the other parameter vectors should be N long. Initial conditions should be Nx2 if we are modeling 2 variables, or Nx3 if we are modeling 3.

Constants

```{r}
#constants for the type of simulation we run

set.seed(46)
#number of regions
N <- 4

#height of air above the Inland Empire that is susceptible to pollution (m)
H <- 1500

#volume of each region (m^3)
V <- 2.7*10^10 * H / N

#warehouse growth mean from logistic fit
warehouse_rate_yrs <- 0.0536353459944 #(yr^-1)
warehouse_rate <- warehouse_rate_yrs * 0.00273973 #(day^-1)

#warehouse carrying capacity from logistic fit
warehouse_cap <- 1.1193946263*10^9 #sqft

#number of warehouses at start of data
warehouses_0 <- sqft_yearly$logistic_pred[1] #sqft

#what year should we start showing our data at?
start_year <- 2020
end_year <- 2030
```

System of ODEs itself:

```{r}
#Parameters
parameters <- list(
  a = c(0.2, 0.2, 0.3, 0.3), #trucks going to park, should add to 1 since most trucks have a 11 hour daily limit
  b = rnorm(N, mean = warehouse_summary$b[1], sd = 0.00001), #(trucks/day/sqft of warehouse)
  #trucks starting their journeys, a random number with the mean being the average amount of trips per day that a square foot of warehosue produces in Southern CA.

  C = matrix(c(0, 0.1, 0, 0,
               0.3, 0, 0.2, 0.1,
               0, 0.2, 0, 0,
               0, 0.2, 0, 0), 
             ncol = N), #Truck travel matrix, fraction of trucks moving between the regions
            
  
  w1 = rnorm(N, warehouse_rate, sd = 0.00001), #warehouse growth rate
  w2 = rnorm(N, warehouse_cap, sd = 0.1*10^9) / N, #warehouse carrying capacity
  
  pm = 10, #trucks PM emissions rate
  pm_disp = 4, #PM dispersal rate
  
  co2 = 10, #trucks CO2 emissions rate
  co2_disp = 4, #CO2 dispersal rate
  
  nox = 10, #trucks NOx emissions rate
  nox_disp = 4 #NOx dispersal rate
  )

#Initial Conditions
Y <- c(
  300, 1800, 1000, 2000, #initial trucks
  rnorm(N, warehouses_0, 100000000) / N, #initial warehouses
  8, 8, 8, 8, #initial PM in the air (micrograms/m^3)
  0, 0, 0, 0, #initial CO2 in the air (g)
  0, 0, 0, 0 #initial NOx in the air()
)


#Growth function
truck_growth <- function(t, Y, parameters) {
dY <- c()
 with(as.list(c(Y, parameters)),{
 # rate of change
   #Y[i] is trucks,
   #Y[i + N] is warehouses
   #Y[i + 2N] is PM
   #Y[i + 3N] is CO2
   #Y[i + 4N] is NOx
      for (i in 1:N){
        dY[i] <- parameters$b[i] * Y[i + N] - 
          parameters$a[i] * Y[i] - 
          sum(parameters$C[,i]) * Y[i] +
          sum(parameters$C[i,] * Y[1:N]) 
        
        dY[i + N] <- parameters$w1[i] * Y[i + N] *
          (1 - (1 / parameters$w2[i]) * 
             Y[i + N])
        
        dY[i + 2*N] <- parameters$pm * Y[i] - parameters$pm_disp * Y[i + 2*N]
        
        dY[i + 3*N] <- parameters$co2 * Y[i] - parameters$co2_disp * Y[i + 3*N]
        
        dY[i + 4*N] <- parameters$nox * Y[i] - parameters$nox_disp * Y[i + 4*N]
      }
    # return the rate of change
    list(dY)
 })
}

#time step and how long to run ODE
total_days <- (end_year - 1980) * 365.25
time_step <- 0.1 #sample it every 0.1 days
max_time <- total_days #run for this many days
times <- seq(0, max_time, by = time_step)

#Run
truck_growth_results <- ode(y = Y, times = times, func = truck_growth, parms = parameters) |>
  as_tibble() 
```

Data wrangling

```{r}
limit <- (start_year - 1980) * 365.25

trucks <- truck_growth_results |>
  select(1:(N + 1)) |>
  mutate(total_trucks = rowSums(across(2:(N + 1)))) |>
  filter(time > limit) |>
  mutate(time = time - limit)

warehouses <- truck_growth_results |>
  select(1, (N + 2):(2*N + 1)) |>
  mutate(total_warehouses = rowSums(across(2:(N + 1)))) |>
  filter(time > limit) |>
  mutate(time = time - limit)

PM <- truck_growth_results |>
  select(1, (2*N + 2):(3*N + 1)) |>
  mutate(total_pollution = rowSums(across(2:(N + 1))))|>
  filter(time > limit) |>
  mutate(time = time - limit)

CO2 <- truck_growth_results |>
  select(1, (3*N + 2):(4*N + 1)) |>
  mutate(total_warehouses = rowSums(across(2:(N + 1)))) |>
  filter(time > limit) |>
  mutate(time = time - limit)

NOx <- truck_growth_results |>
  select(1, (4*N + 2):(5*N + 1)) |>
  mutate(total_warehouses = rowSums(across(2:(N + 1)))) |>
  filter(time > limit) |>
  mutate(time = time - limit)
```

Plotting

```{r}
#R vs time graph
trucks |>
ggplot() +
  geom_line(aes(x = time, y = total_trucks)) +
  theme_classic() +
  labs(
    title = "Total Trucks vs Time",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time (days)",
    y = "Total Trucks"
  )

```

```{r}
trucks |>
  pivot_longer(2:(N + 1), names_to = "region", values_to = "trucks") |>
  select(time, region, trucks, total_trucks) |>
  ggplot(aes(x = time)) +
  geom_line(aes(y = trucks, color = region)) +
  geom_line(aes(y = total_trucks, color = "Total")) +
  theme_classic() +
  labs(
    title = "Trucks vs Time by Region",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time (days)",
    y = "Trucks",
    legend = "Region"
  )
```

```{r}
#W vs time graph
warehouses |>
ggplot(aes(x = time, y = total_warehouses)) +
  geom_line() +
  theme_classic() +
  labs(
    title = "Total Warehouses vs Time",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time (days)",
    y = "Total Warehouses Area (sq. ft.)"
  )

```

```{r}
warehouses |>
  rename_with(~as.character(seq_along(.x)), .cols = 2:(N + 1)) |>
  pivot_longer(2:(N + 1), names_to = "region", values_to = "warehouses") |>
  select(time, region, warehouses, total_warehouses) |>
  ggplot(aes(x = time)) +
  geom_line(aes(y = warehouses, color = region)) +
  geom_line(aes(y = total_warehouses, color = "Total")) +
  theme_classic() +
  labs(
    title = "Warehouses vs Time by Region",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time",
    y = "Warehouses",
    legend = "Region"
  )
```

```{r}
#Pollution vs time graph
PM |>
ggplot(aes(x = time, y = total_pollution)) +
  geom_line() +
  theme_classic() +
  labs(
    title = "Total Particulate Matter (PM) vs Time",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time (days)",
    y = "Total PM (μg/m^3)"
  )
```

```{r}
PM |>
  rename_with(~as.character(seq_along(.x)), .cols = 2:(N + 1)) |>
  pivot_longer(2:(N + 1), names_to = "region", values_to = "pollution") |>
  select(time, region, pollution, total_pollution) |>
  ggplot(aes(x = time)) +
  geom_line(aes(y = pollution, color = region)) +
  geom_line(aes(y = total_pollution, color = "Total")) +
  theme_classic() +
  labs(
    title = "Total Particulate Matter (PM) vs Time",
    subtitle = str_c("Starting in ", start_year, ", ending in ", end_year),
    x = "Time (days)",
    y = "Total PM (μg/m^3)",
    legend = "Region"
  )
```
