---
title: "Truck Modeling"
format: html
editor: visual
---

```{r}
library(deSolve)
library(tidyverse)
```

Create DE

```{r}


truck_model <- function(square, param_a, param_b, param_c, param_d, param_w){
#Parameters
parameters <- c(
  a = param_a,
  b = param_b,
  
  c1 = param_c[1],
  c2 = param_c[2],
  c3 = param_c[3],
  c4 = param_c[4],
  
  d1 = param_d[1],
  d2 = param_d[2],
  d3 = param_d[3],
  d4 = param_d[4],
  
  w1 = param_w[1],
  w2 = param_w[2]
  )

#Initial Conditions
state <- c(
  R = 1,
  W = 1
)


#Growth function
truck_growth <- function(t, state, parameters) {
 with(as.list(c(state, parameters)),{
 # rate of change
  dR <- b*W - a*R - d1*R - d2*R - d3*R - d4*R
  dW <- w1*(1 - w2*W)

 # return the rate of change
 list(c(dR, dW))
 })
}

#time step and how long to run ODE
time_step <- 0.01
max_time <- 100
times <- seq(0, max_time, by = time_step)

#Run
truck_growth_results <- ode(y = state, times = times, func = truck_growth, parms = parameters) |>
  as_tibble() |>
  mutate(square = square)
truck_growth_results
}

truck_model("Test Square", 
            1, #a parameter
            1, #b parameter
            c(1, 1, 1, 1), #c parameter vector
            c(0, 0, 0, 0.5), #d parameter vector
            c(0.5, 0.5) #w parameter vector
)
```

```{r}
#R vs time graph
ggplot(truck_growth_results) +
  geom_line(aes(x = time, y = R)) +
  theme_classic()

#W vs time graph
ggplot(truck_growth_results) +
  geom_line(aes(x = time, y = W)) +
  theme_classic()
```

```{r}
truck_model <- function(square, param_a, param_b, param_c, param_d, param_w){
#Parameters
parameters <- c(a = 1, b = 1, w1 = 1, w2 = 1
  )

#Initial Conditions
state <- c(
  R = 1,
  W = 1
)


#Growth function
truck_growth <- function(t, state, parameters) {
 with(as.list(c(state, parameters)),{
   
 # rate of change
  dR <- b*W - a*R
  dW <- w1*(1 - w2*W)

 # return the rate of change
 list(c(dR, dW))
 })
}

#time step and how long to run ODE
time_step <- 0.01
max_time <- 100
times <- seq(0, max_time, by = time_step)

#Run
truck_growth_results <- ode(y = state, times = times, func = truck_growth, parms = parameters) |>
  as_tibble() |>
  mutate(square = square)
truck_growth_results
}

```

Make it into a lot of squares

```{r}
truck_model("test", 
                       1, #a parameter
                       1, #b parameter
                       c(1,1,1,1), #c parameter vector
                       c(1,1,1,1), #d parameter vector
                       c(0.5,0.5) #w parameter vector
                       ) |>
  list_rbind() |>
  arrange(time)


```

Make it so that you can change the parameters

```{r}
#list of parameters for each square
all_a <- list(1, 1, 3, 2, 1, 2, 3, 4, 1, 3)
all_b <- list(2, 1, 2, 3, 4, 1, 2, 3, 2, 3)
all_c <- list(
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1)
)
all_d <- list(
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1),
  c(1, 1, 1, 1)
)
all_w <- list(
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5),
  c(0.5, 0.5)
)
param_list <- list(list(1:10), all_a, all_b, all_c, all_d, all_w)

#try to make the function work
pmap(param_list, ~truck_model(..1, ..2, ..3, ..4, ..5, ..6)) |>
  list_rbind() |>
  arrange(time)
```

Plot DE

```{r}
a1 <- 1
a2 <- 3
a3 <- 4

W1 <- 3
W2 <- 3
W3 <- 2

#R_vec <- matrix(c(R1, R2, R3), nrow = 1, ncol = 3)
W_vec <- matrix(c(W1, W2, W3), nrow = 1, ncol = 3)
a_matrix <- matrix(c(a1, a2, a3), nrow = 3, ncol = 3)
#b_matrix <- matrix(c(b1, b2, b3), nrow = 3, ncol = 3)


```
